/**
 * 値オブジェクト統合公開API
 * 全ての値オブジェクトの統一的なエクスポート
 */

// Money値オブジェクト
export type {
  Money,
  Currency,
  MoneyComparison,
  MoneyFormatOptions,
} from './money';

export {
  MoneyError,
  CurrencyMismatchError,
  InvalidAmountError,
  CURRENCY_SYMBOLS,
  CURRENCY_NAMES_JA,
  CURRENCY_NAMES_EN,
  CURRENCY_DECIMAL_PLACES,
  DEFAULT_CURRENCY,
  ZERO_MONEY,
  MAX_SAFE_AMOUNT,
  MIN_SAFE_AMOUNT,
  createMoney,
  validateAmount,
  assertSameCurrency,
  addMoney,
  subtractMoney,
  multiplyMoney,
  divideMoney,
  compareMoney,
  isEqualMoney,
  isZero,
  isPositive,
  isNegative,
  absoluteMoney,
  negateMoney,
  sumMoney,
  formatMoney,
  formatMoneyCompact,
  parseMoney,
} from './money';

// Email値オブジェクト
export type { Email, EmailValidationOptions, ParsedEmail } from './email';

export {
  EmailValidationError,
  EMAIL_VALIDATION,
  EMAIL_REGEX,
  STRICT_EMAIL_REGEX,
  LOCAL_PART_REGEX,
  DOMAIN_PART_REGEX,
  DISPOSABLE_EMAIL_DOMAINS,
  FORBIDDEN_LOCAL_PATTERNS,
  DEFAULT_VALIDATION_OPTIONS,
  isValidEmailFormat,
  isStrictValidEmailFormat,
  parseEmail,
  validateEmail,
  createEmail,
  normalizeEmail,
  emailToString,
  getEmailDomain,
  getEmailLocal,
  maskEmail,
  isDisposableEmail,
  areEmailsEqual,
} from './email';

// Date値オブジェクト
export type {
  ISODateString,
  DateString,
  TimeString,
  MonthString,
  DateFormatOptions,
  TimeFormatOptions,
  DateRange,
  MonthRange,
  Period,
  RelativeDate,
} from './date';

export {
  DateValidationError,
  TimeValidationError,
  PeriodValidationError,
  DATE_REGEX,
  WEEKDAY_NAMES_JA,
  WEEKDAY_NAMES_SHORT_JA,
  MONTH_NAMES_JA,
  MONTH_NAMES_EN,
  MONTH_NAMES_SHORT_EN,
  DEFAULT_DATE_FORMAT,
  DEFAULT_TIME_FORMAT,
  DATE_BOUNDS,
  TIME_BOUNDS,
  DAYS_IN_MONTH,
  DAYS_IN_MONTH_LEAP,
  MILLISECONDS,
  isLeapYear,
  validateDateString,
  validateTimeString,
  validateMonthString,
  createDateString,
  createTimeString,
  createMonthString,
  createISODateString,
  dateToDateString,
  dateToTimeString,
  dateToMonthString,
  dateToISOString,
  dateStringToDate,
  isoStringToDate,
  now,
  today,
  thisMonth,
  addDays,
  addMonths,
  addYears,
  addRelativeDate,
  diffInDays,
  compareDates,
  validateDateRange,
  isDateInRange,
  formatDate,
  formatTime,
  getFirstDayOfMonth,
  getLastDayOfMonth,
  monthRangeToDateRange,
} from './date';
