# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - tmp
    - scripts
  skip-files:
    - ".*_test.go"

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - unconvert
    - gosec
    - gocyclo
    - dupl
    - goconst
    - gocritic
    - typecheck
    - revive
    - staticcheck

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - linters:
        - staticcheck
      text: "SA1019:"

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0